### ISSUE TITLE
A question for square ctf challenge deepblog.

### ISSUE THREAD

**Issue by krnbhargav** [ryan-cd/ctf#1]
how you are able to find App.js(frontend code) i am not able to find that on this website.
http://challenges.2020.squarectf.com:9541/

**Comment by ryan-cd** [comment]
Hey @krn-bhargav!

In Chrome I opened the Sources tab in the developer tools to find it:

![image](https://user-images.githubusercontent.com/5481444/99187986-b9d6c500-2727-11eb-9a21-2cd108be7880.png)

**Comment by krnbhargav** [comment]
ok now i got,i was mistakenly try at source code of website
